[package]
name = "price_feed_demo"
version = "1.0.0"
authors = []

[addresses]
price_feed = "_"
owner = "0xb3c4f75936dc2f8af0398408a7ef739cca2601439be9100eb7a792c475923d1"
data_feeds = "0x3f985798ce4975f430ef5c75776ff98a77b9f9d0fb38184d225adc9c1cc6b79b"
platform = "0x9976bb288ed9177b542d568fa1ac386819dc99141630e582315804840f41928a"
platform_secondary = "0x3bcacb561438c55ce2a9da479df6ab486af55b2fb7070b700df36c097da732b8"
owner_secondary = "0xc71bcbcaf97ee6d54d9a128078e214e9578ee5b165c6a1c047b5c0271c8aaff5"
move_stdlib = "0x1"

[dev-addresses]
price_feed = "0x11"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }
ChainlinkDataFeeds = { git = "https://github.com/smartcontractkit/chainlink-aptos.git", subdir = "contracts/data-feeds", rev = "develop" }

[dev-dependencies]
